[package]
name = "mksubrip"
version = "0.1.0"
edition = "2021"
author = "George Cai <georgecai0908@outlook.com>"

[dependencies]
anyhow = "1.0.80"
chrono = "0.4.35"
eframe = "0.26.2"
env_logger = "0.11.3"
log = "0.4.21"
rfd = "0.14.0"
